export { default as DiscountSlider } from './DiscountSlider'
export { default as MainSlider } from './MainSlider'
export { default as BestSellsSlider } from './BestSellsSlider'
export { default as SmilarProductsSlider } from './SmilarProductsSlider'
export { default as ProductFavouriteSlider } from './ProductFavouriteSlider'
