export { default as ReveiwSkeleton } from './ReveiwSkeleton'
export { default as NavbarSkeleton } from './NavbarSkeleton'
export { default as SidebarSkeleton } from './SidebarSkeleton'
export { default as OrderSkeleton } from './OrderSkeleton'
export { default as ProductSkeleton } from './ProductSkeleton'
export { default as SubCategoriesSkeleton } from './SubCategoriesSkeleton'
export { default as TableSkeleton } from './TableSkeleton'
export { default as AddressSkeleton } from './AddressSkeleton'
